### ISSUE TITLE
Possible Memory Leak for K8s logs

### ISSUE THREAD

**Issue by arch-xtof** [vectordotdev/vector#14750]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

# Description of the environment
There is vector DaemonSet in the k8s cluster, each Pod collects k8s logs

# Expectation
After upgrading Vector from `0.20.0` to `0.21.2` there is not much difference in memory usage

# Actuall Outcome
On some nodes, Vector memory usage keeps linearly increasing causing them to be OOM-Killed by k8s. The same issue persists in all versions including `0.24.1`

## Memory usage graphs
Updated version at ~11:20
**All pods**
![image](https://user-images.githubusercontent.com/60723394/194296975-30bb1fce-7f42-463d-ab05-2eb0e643d5dd.png)

**Problematic Pods**
![image](https://user-images.githubusercontent.com/60723394/194297091-df48b08c-47bd-4eed-83e6-a0bdbde3de4b.png)

### Configuration

```text
# Vector's API for introspection
    [api]
      enabled = true
      address = "0.0.0.0:yyyy"

    # Read Kubernetes logs from files
    [sources.kube_logs_1]
      type = "kubernetes_logs"
      exclude_paths_glob_patterns = ["xxx"]
      annotation_fields.container_name = "container_name"
      annotation_fields.container_image = "container_image"
      annotation_fields.pod_ip = "pod_ip"
      annotation_fields.pod_name = "pod_name"
      annotation_fields.pod_namespace = "namespace_name"
      annotation_fields.pod_node_name = "pod_node_name"
      annotation_fields.pod_uid = "pod_uid"

    # Transform Kube logs and remove unused fields
    [transforms.kube_logs_remapped]
      type = "remap"
      inputs = ["kube_logs_1"]
      source = '''
      .full_message = .message
      .message = "pod_stderr_stdout"
      .source = .pod_name
      .node_name = .pod_node_name
      .facility = .container_name
      del(.file)
      del(.pod_node_name)
      del(.kubernetes)
      '''

    # Filter OUT k8s-event-logger events
    [transforms.kube_logs_filtered]
      type = "filter"
      inputs = ["kube_logs_remapped"]
      condition = '.container_name != "k8s-event-logger"'

    # Filter IN k8s-event-logger events
    [transforms.only_k8s_event_logs]
      type = "filter"
      inputs = ["kube_logs_1"]
      condition = '.container_name == "k8s-event-logger"'

    # Transform k8s event logs from JSON
    [transforms.k8s_events_remapped]
      type = "remap"
      inputs = ["only_k8s_event_logs"]
      source = '''
      if is_nullish(.message) == true {
        .message = "No log message attached for k8s-event-logger"
        .facility = "k8s-event-logger"
        abort
      }
      . = parse_json!(.message)
      .facility = "k8s-event-logger"
      .type = .type
      .reason = .reason
      .namespace_name = .metadata.namespace
      .node_name = .source.host
      .source = .involvedObject.name
      .object_kind = .involvedObject.kind
      .object_name = .involvedObject.name
      del(.metadata)
      del(.involvedObject)
      del(.count)
      del(.firstTimestamp)
      del(.lastTimestamp)
      del(.reportingComponent)
      del(.reportingInstance)
      del(.eventTime)
      '''

    # Forward logs to vector-aggregator service
    [sinks.vector_aggr]
      type = "vector"
      inputs = ["k8s_events_remapped", "kube_logs_filtered"]
      address = "x.x.x.x:yyyy"
```

### Version

`>=0.21.0-distroless-libc`

### Additional Context

* Vector is deployed as DaemonSet in k8s
* It is collecting k8s logs

**Comment by spencergilbert** [comment]
I believe this is a duplicate, or result, of the issue described in https://github.com/vectordotdev/vector/issues/11995.

[expire_metrics_secs](https://vector.dev/docs/reference/configuration/global-options/#expire_metrics_secs) can be set to remove old metrics periodically to avoid this continual growth.

Please let me know if that doesn't resolve the issue.

**Comment by arch-xtof** [comment]
Hello again, seems that the issue still persists after including `expire_metrics_secs = 60` in the config. This time it is version 0.24.1

First spike is upgrade from 0.20.0 to 0.24.1, while second spike is related to restart of the pods
![image](https://user-images.githubusercontent.com/60723394/194557458-4df0f3a7-d966-4f67-a5d6-51fc7ef0566f.png)

Any other information, that I can provide?

**Comment by spencergilbert** [comment]
🤔 could you clarify the Y-axis on these graphs? Another metric that would be interesting to see is: https://vector.dev/docs/reference/configuration/sources/internal_metrics/#internal_metrics_cardinality

**Comment by arch-xtof** [comment]
The Y-axis graph refers to memory usage in MB. Here is the metric of `internal_metric_cardinality`:
**Top 5 Cardinality**
![image](https://user-images.githubusercontent.com/60723394/194611163-404bfba7-a1b4-4540-b5fc-6a5014417b92.png)

**All**
![image](https://user-images.githubusercontent.com/60723394/194611338-1b71e0f6-a6a9-43e5-a09b-86d79a6b3e71.png)

For some reason, cardinality is still increasing all the time, but I don't see a strong correlation between cardinality and memory usage.

**Comment by spencergilbert** [comment]
Thanks, and this is with `expire_metrics_secs` enabled?

**Comment by arch-xtof** [comment]
Yes, `expire_metrics_secs = 60` is part of the config. Also, would debug logs be useful in this case? I checked myself but could not find anything interesting.

**Comment by leandrojmp** [comment]
I have a simular issue of memory leak, opened an issue a couple of months ago, [#11025](https://github.com/vectordotdev/vector/issues/11025), and was waiting for this to be fixed, but the issue persists.

I'm running `0.24.1` and have `expire_metrics_secs` set to `30`, my source are files and my sinks are kafka, the vector memory keeps increasing.

**Comment by spencergilbert** [comment]
> It is possible to entirely disable the generation of these metrics to see if this solve the issue?

Right now that would require a custom build, I believe. CC @jszwedko and @bruceg as another report of metrics not expiring issue.

**Comment by leandrojmp** [comment]
Hello @spencergilbert,

A custom build with code change or some flags while compiling? Is there is some flag to disable building with metrics, I could try a custom build.

**Comment by spencergilbert** [comment]
OK, so I talked with @jszwedko and it turns out I've completely mixed up when fixes are/were released. I think this _should_ be fixed in `0.24.2` (cutting this week) between https://github.com/vectordotdev/vector/issues/14394 and https://github.com/vectordotdev/vector/pull/14423. This _should_ be testable on a nightly image without any custom builds required.

**Comment by leandrojmp** [comment]
Thanks @spencergilbert!

I will update to `0.24.2` when it becames available and check the behavior.

**Comment by arch-xtof** [comment]
Hey! I just tested the nightly build, and the cardinality issue is resolved, but the memory issue persists.
![image](https://user-images.githubusercontent.com/60723394/195583098-0f28b97b-d5b5-436c-ace8-47037d606296.png)

**Comment by jszwedko** [comment]
Thanks for the report back @arch-xtof ! It's disappointing that that didn't resolve the issue for you. I see above that you mentioned you started seeing the regression in behavior from v0.20.0 to v0.21.2. One thing we could try is bisecting down the nightly versions between those two releases to find the nightly version that induces the behavior change. This would narrow down the set of commits to examine. Would you be open to that? That would mean bisecting down the nightly versions from 2022-02-10 through 2022-04-14.

**Comment by arch-xtof** [comment]
Yes, I can first check the subversions, and then the nightly builds between them. I'll divide periods into halves to speed up the process, though this still is going take some time.

**Comment by leandrojmp** [comment]
Hello @jszwedko,

I don't know if it is the same cause, but I've been having this memory leak issue since vector `0.19`.

**Comment by arch-xtof** [comment]
So, after testing the nightly builds it seems that the problem starts appearing on the 15th of March (`nightly-2022-03-15-distroless-libc`). The build  - `nightly-2022-03-14-distroless-libc` seems stable in terms of memory but still has significantly higher usage on some nodes in comparison to version `0.20.1`. 
![image](https://user-images.githubusercontent.com/60723394/196668555-723f6a3c-bb1d-4d49-840b-9d6983fda2cb.png)

**Comment by jszwedko** [comment]
Awesome, thank you so much for narrowing that down @arch-xtof !

Looking at those two nightlies, it seems like the range of commits should be https://github.com/vectordotdev/vector/compare/48ab784...3397283


```
$ docker run -it timberio/vector:nightly-2022-03-14-distroless-libc --version
vector 0.21.0 (aarch64-unknown-linux-gnu 48ab784 2022-03-14)
$ docker run -it timberio/vector:nightly-2022-03-15-distroless-libc --version
vector 0.21.0 (aarch64-unknown-linux-gnu 3397283 2022-03-15)
```

Of those commits, the only one that seems like it could plausibly be the culprit is https://github.com/vectordotdev/vector/commit/75002242b2e2083454772300a2d79fb1621b1de2 but nothing immediately jumps out about it. I'll surface it with the team to get their thoughts.

**Comment by arch-xtof** [comment]
Yes, I checked the commits in that time frame and there was nothing related to the `kubernetes_logs` source. I can also play around with the config sections and narrow down the scope even further. For example, I can try to remove the `vector` sink and see what happens.

**Comment by jszwedko** [comment]
Just leaving a note for reference that I talked with @tobz who thinks this could be related to clones in the retry layer. They mentioned we could make the clones cheaper by switching the `vector` sink to use `Bytes`.

I'll see if I can find some time to reproduce this locally to profile and/or make tweaks to see if it impacts the memory usage.

**Comment by arch-xtof** [comment]
Hello! Any updates regarding this?

**Comment by arch-xtof** [comment]
I was looking into metrics and noticed that pods that are subject to a memory leak, constantly keep opening new files
![image](https://user-images.githubusercontent.com/60723394/202808972-bb190101-84de-41b2-9c2d-e4689ba652a3.png)

**Comment by leandrojmp** [comment]
I think it is similar to my case, I'm download thousands of files per hour for vector to process and send to kafka.

The memory has a similar behavior.

**Comment by bruceg** [comment]
Given the connection with open files, I am wondering if the nightly testing above didn't hit a false negative and this issue actually related to #11742.

**Comment by leandrojmp** [comment]
@bruceg In my case, which is this issue #11025, I'm deleting the files after vector processes them.

I didn't notice any disk issue related to inodes, but I'm restarting vector every 12 hours to avoid it being killed by an OOM issue, maybe in my case the OOM is hitting first than any disk issue.

I could check for any inode/disk issues on monday.

**Comment by arch-xtof** [comment]
For me, it seems that both factors are related. I went through most of the metrics and noticed the following things
* instances that are leaking memory constantly open new files
* If the sink is switched from `vector` to `blackhole` this behavior stops
* `vector` sink utilization is somewhat the opposite of memory usage

Annotations:
1. Upgraded vector from `0.20.1` to `0.25.1`
2. Pods got OOM Killed
3. Switched `vector` sink to `blackhole`

![image](https://user-images.githubusercontent.com/60723394/202848123-64b9c9de-e01f-4479-bd09-d41b9ac6b55d.png)

**Comment by leandrojmp** [comment]
@arch-xtof did you updated to 0.26? If yes, do you still have this issue?

**Comment by arch-xtof** [comment]
@leandrojmp no I haven't updated yet, but I am planning to check it out today/tomorrow.

**Comment by arch-xtof** [comment]
After observing `0.26.0` for a few days, I can say that the issue persists but seems to occur way more rarely. As previously mentioned, the pods running out of memory are the ones opening new files endlessly.

![image](https://user-images.githubusercontent.com/60723394/208089572-5b23e47d-e1f3-46bf-8705-7f29e73d61e0.png)

Next week I'll try to figure out what is different on the nodes where these pods run.

**Comment by fpytloun** [comment]
Unfortunately I am seeing same issue with `file` sink. Using `expire_metrics_secs` lowers incoming internal_metrics but doesn't lower resource usage so pod dies on OOM once in a while.

**Comment by arch-xtof** [comment]
I have been running `0.26.0` for quite a while now. As I mentioned the occurrence of this issue has decreased significantly but persisted on some specific nodes. I looked into those nodes and found out that they run some malfunctioning pods which log an insane amount of data. 

My first idea was to use the `throttle` transform.

![image](https://user-images.githubusercontent.com/60723394/213417257-6e6549b2-6b4a-4579-b59d-63204900e5e6.png)
*Vector changes after configuring throttle transform*

It fixed or more of slowed down (visible in the next picture) the problem with memory but created the problem of endlessly opening files.

![image](https://user-images.githubusercontent.com/60723394/213422176-d632ecad-83d2-4382-abfb-b5bd4efcb1f4.png)
*Memory usage growing slowly with count of open files*

Looking into the `/var/log/pods/` folder of the offending container, I noticed, that there are not that many files there. Yet these files are constantly changing. Here is the output of the ls command issued within quite short intervals of time.

`10.log  10.log.20230119-085528  9.log  9.log.20230119-083209`

`10.log  10.log.20230119-085628  9.log  9.log.20230119-083209`

`10.log  10.log.20230119-085649  9.log  9.log.20230119-083209`

`10.log  10.log.20230119-092554  11.log  11.log.20230119-093928`

I suspect that Vector keeps the deleted files open. To verify that my findings are correct I disabled the collection of logs from this specific pod and the issue got resolved.

![image](https://user-images.githubusercontent.com/60723394/213420412-327f4bb5-f5fb-4ecb-91d4-b49fa3fbe49d.png)
*Metrics stabilizing after ignoring offending pod*

Does Vector offer any other ways to handle these kinds of cases or is this something that can be implemented in the future?

**Comment by aashery-square** [comment]
We're seeing this behavior for vector 0.29.1 on EKS 1.24. We are load testing vector by running it as a daemonset against pods writing files via the `json-file` log driver for containerd. There's 32 pods writing 100 logs/s each, so we're pushing 3200 logs/s through the vector daemon on the node. Log sizes vary from 1.25K-128K, with mostly smaller writes. We see unbounded memory growth consistently even when setting a blackhole sink (contrary to what @arch-xtof experienced). Based on log throughput and EKS' rotation size I'd imagine that we're rotating through a ton of files, so agree that Vector is probably hoarding open file handles.

# Setup
## Chart.yaml
```yaml
apiVersion: v2
name: service
type: application
version: 1.0.0
dependencies:
  - name: vector
    version: 0.21.1
    repository: "https://helm.vector.dev"
```

## Values.yaml
```yaml
podLabels:
  tags.datadoghq.com/version: 0.29.1
resources:
  limits:
    cpu: 3000m
    memory: 1Gi
  requests:
    cpu: 3000m
    memory: 1Gi
```

## Vector Config
The redacted remaps below are just adding additional static tags.
```yaml
data_dir: /vector-data-dir
expire_metrics_secs: 60

api:
  enabled: true
  address: 127.0.0.1:8686
  playground: false

sources:
  internal_logs:
    type: internal_logs
  internal_metrics:
    type: internal_metrics
    scrape_interval_secs: 30
    tags:
      host_key: host
  k8s_logs:
    type: kubernetes_logs
    glob_minimum_cooldown_ms: 15000

transforms:
  vector_tagging:
    type: remap
    inputs:
      - internal_metrics
    source: |
      .tags.region = get_env_var!("AWS_REGION")
      ...(REDACTED)...
  log_tagging:
    type: remap
    inputs:
      - internal_logs
    source: |
      .service = "vector-daemonset"
      ...(REDACTED)...
sinks:
  datadog_metrics:
    type: datadog_metrics
    inputs:
      - vector_tagging
    default_api_key: ${DATADOG_API_KEY}
  datadog_logs:
    type: datadog_logs
    inputs:
      - log_tagging
    default_api_key: ${DATADOG_API_KEY}
  null_out:
    type: blackhole
    inputs:
      - k8s_logs
```

# Results
![image](https://user-images.githubusercontent.com/102249205/236337375-d26f94e0-a05b-428b-a812-4102c77d7d48.png)
