### ISSUE TITLE
Metrics are not being expired even with expire_metrics_secs set.

### ISSUE THREAD

**Issue by leandrojmp** [vectordotdev/vector#14789]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

Hello,

I've upgraded my vector instance to `0.24.1` to be able to use the `expire_metrics_secs` options, to see if this would solve a memory leak issue that I'm having since I started using vector ([#11025](https://github.com/vectordotdev/vector/issues/11025)).

From the description of #11995 it seems that `expire_metrics_secs` would help solve this issue, but after setting `expire_metris_secs` to `30`  in my vector settings, the issue persists, the memory keeps increasing and it seems that the metrics are not being expired.

This is the monitoring of the memory for the vector process, when the graphic falls it is because of a restart of the service.

![vector-leak](https://user-images.githubusercontent.com/322886/194883975-59944c8b-ac3a-484c-91b3-59ada062ec31.png)

I'm using a config directory with my vector pipelines, so I have the following variable in `/etc/default/vector`

```
VECTOR_CONFIG_DIR="/data/vector/pipelines/"
VECTOR_LOG="ERROR"
```

In this path I have a `global.toml` with the following configuration:

```
# vector global options
expire_metrics_secs = 30
data_dir = "/data/vector/db"
```

Then I have around 14 configuration files using the `file` source and the `kafka` sink, each one reading from a different path and sending to a different kafka topic.

### Configuration

```text
[sources.SOURCE_REDACTED]
type = "file"
include = ["/REDACTED/*/*/*.json"]
read_from = "beginning"
ignore_older_secs = 43200
remove_after_secs = 1
oldest_first = true
ignore_checkpoints = true
fingerprint.strategy = "device_and_inode"

[sinks.SINK_REDACTED]
type = "kafka"
inputs = [ "SOURCE_REDACTED" ]
bootstrap_servers = "KAFKA-BROKERS"
message_timeout_ms = 300_000
socket_timeout_ms = 60_000
topic = "KAFKA-TOPIC"
compression = "gzip"
encoding.codec = "text"
buffer.max_events = 1000
```

### Version

vector 0.24.1 (x86_64-unknown-linux-gnu 8935681 2022-09-12)

### References

#11995

**Comment by zamazan4ik** [comment]
@jszwedko @spencergilbert @neuronull Do you have an update? Seems like kinda critical issue.

**Comment by jszwedko** [comment]
Hey all,

This issue was fixed, but unreleased yet. We are hoping to release 0.24.2 tomorrow or Thursday which will include this.

**Comment by zamazan4ik** [comment]
@leandrojmp Will you be able to test the newer release in your env and confirm that the fix works?

**Comment by leandrojmp** [comment]
@zamazan4ik Sure, I will update to `0.24.2` when it becames available and monitor the vector process memory to see if the current behavior changes.

**Comment by leandrojmp** [comment]
I've just updated to `0.24.2` and will monitor the memory to see if the issue is solved.

**Comment by leandrojmp** [comment]
Unfortunatelly the issue persists, the metrics are not being expired and the memory usage keeps increasing.

![vector-issue](https://user-images.githubusercontent.com/322886/195854953-41026b2f-d0b2-487c-9f78-dddd29487410.png)

**Comment by zamazan4ik** [comment]
@jszwedko please take a look.

**Comment by jszwedko** [comment]
Can you share a graph of `vector_internal_metrics_cardinality` alongside the memory graph (i.e. covering the same time ranges)?

**Comment by leandrojmp** [comment]
Hello @jszwedko,

I'm not monitoring vector, but using the following configuration I was able to capture the metrics temporarily:

```
[sources.vector_metrics]
type = "internal_metrics"
scrape_interval_secs = 10

[sinks.kafka_metrics]
type = "kafka"
inputs = [ "vector_metrics" ]
bootstrap_servers = "KAFKA-BROKERS"
message_timeout_ms = 300_000
socket_timeout_ms = 60_000
topic = "vector-metrics"
compression = "gzip"
encoding.codec = "text"
buffer.max_events = 1000
```
It looks like that the metrics are indeed being expired, as the value of `vector_internal_metrics_cardinality` has huge drops every 30 seconds, which is the value of `expire_metrics_secs`, but the memory keeps growing and will hit an OutOfMemory error if the process is not restarted.

I let it run for around 10 minutes, and this is the result:

```2022-10-14T18:40:23.763943196Z vector_internal_metrics_cardinality{} = 40
2022-10-14T18:40:23.763943196Z vector_internal_metrics_cardinality_total{} = 40
2022-10-14T18:40:43.754762714Z vector_internal_metrics_cardinality{} = 107
2022-10-14T18:40:43.754762714Z vector_internal_metrics_cardinality_total{} = 107
2022-10-14T18:40:53.754201725Z vector_internal_metrics_cardinality{} = 107
2022-10-14T18:40:53.754201725Z vector_internal_metrics_cardinality_total{} = 107
2022-10-14T18:41:13.754693554Z vector_internal_metrics_cardinality{} = 89
2022-10-14T18:41:13.754693554Z vector_internal_metrics_cardinality_total{} = 89
2022-10-14T18:41:23.754533139Z vector_internal_metrics_cardinality{} = 89
2022-10-14T18:41:23.754533139Z vector_internal_metrics_cardinality_total{} = 89
2022-10-14T18:42:33.754152838Z vector_internal_metrics_cardinality{} = 34152
2022-10-14T18:42:33.754152838Z vector_internal_metrics_cardinality_total{} = 34152
2022-10-14T18:40:33.754982031Z vector_internal_metrics_cardinality{} = 107
2022-10-14T18:40:33.754982031Z vector_internal_metrics_cardinality_total{} = 107
2022-10-14T18:41:03.754838629Z vector_internal_metrics_cardinality{} = 89
2022-10-14T18:41:03.754838629Z vector_internal_metrics_cardinality_total{} = 89
2022-10-14T18:41:33.755017735Z vector_internal_metrics_cardinality{} = 89
2022-10-14T18:41:33.755017735Z vector_internal_metrics_cardinality_total{} = 89
2022-10-14T18:41:43.754648356Z vector_internal_metrics_cardinality{} = 89
2022-10-14T18:41:43.754648356Z vector_internal_metrics_cardinality_total{} = 89
2022-10-14T18:41:53.754533399Z vector_internal_metrics_cardinality{} = 89
2022-10-14T18:41:53.754533399Z vector_internal_metrics_cardinality_total{} = 89
2022-10-14T18:42:03.754515791Z vector_internal_metrics_cardinality{} = 89
2022-10-14T18:42:03.754515791Z vector_internal_metrics_cardinality_total{} = 89
2022-10-14T18:42:13.755351244Z vector_internal_metrics_cardinality{} = 14958
2022-10-14T18:42:13.755351244Z vector_internal_metrics_cardinality_total{} = 14958
2022-10-14T18:42:23.754373258Z vector_internal_metrics_cardinality{} = 25627
2022-10-14T18:42:23.754373258Z vector_internal_metrics_cardinality_total{} = 25627
2022-10-14T18:42:43.757022471Z vector_internal_metrics_cardinality{} = 31021
2022-10-14T18:42:43.757022471Z vector_internal_metrics_cardinality_total{} = 31021
2022-10-14T18:42:53.755154334Z vector_internal_metrics_cardinality{} = 30228
2022-10-14T18:42:53.755154334Z vector_internal_metrics_cardinality_total{} = 30228
2022-10-14T18:43:03.754118758Z vector_internal_metrics_cardinality{} = 36330
2022-10-14T18:43:03.754118758Z vector_internal_metrics_cardinality_total{} = 36330
2022-10-14T18:43:13.754649752Z vector_internal_metrics_cardinality{} = 30277
2022-10-14T18:43:13.754649752Z vector_internal_metrics_cardinality_total{} = 30277
2022-10-14T18:43:23.754536974Z vector_internal_metrics_cardinality{} = 18986
2022-10-14T18:43:23.754536974Z vector_internal_metrics_cardinality_total{} = 18986
2022-10-14T18:43:33.755039990Z vector_internal_metrics_cardinality{} = 11811
2022-10-14T18:43:33.755039990Z vector_internal_metrics_cardinality_total{} = 11811
2022-10-14T18:43:43.754499008Z vector_internal_metrics_cardinality{} = 1225
2022-10-14T18:43:43.754499008Z vector_internal_metrics_cardinality_total{} = 1225
2022-10-14T18:43:53.754651571Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:43:53.754651571Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:44:03.754319703Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:44:03.754319703Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:44:13.754075267Z vector_internal_metrics_cardinality{} = 11324
2022-10-14T18:44:13.754075267Z vector_internal_metrics_cardinality_total{} = 11324
2022-10-14T18:44:23.754405161Z vector_internal_metrics_cardinality{} = 12717
2022-10-14T18:44:23.754405161Z vector_internal_metrics_cardinality_total{} = 12717
2022-10-14T18:44:33.754335654Z vector_internal_metrics_cardinality{} = 12717
2022-10-14T18:44:33.754335654Z vector_internal_metrics_cardinality_total{} = 12717
2022-10-14T18:44:43.754791448Z vector_internal_metrics_cardinality{} = 8915
2022-10-14T18:44:43.754791448Z vector_internal_metrics_cardinality_total{} = 8915
2022-10-14T18:44:53.754107411Z vector_internal_metrics_cardinality{} = 1004
2022-10-14T18:44:53.754107411Z vector_internal_metrics_cardinality_total{} = 1004
2022-10-14T18:45:03.754522943Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:45:03.754522943Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:45:13.754935147Z vector_internal_metrics_cardinality{} = 119
2022-10-14T18:45:13.754935147Z vector_internal_metrics_cardinality_total{} = 119
2022-10-14T18:45:23.754458162Z vector_internal_metrics_cardinality{} = 119
2022-10-14T18:45:23.754458162Z vector_internal_metrics_cardinality_total{} = 119
2022-10-14T18:45:33.754397344Z vector_internal_metrics_cardinality{} = 123
2022-10-14T18:45:33.754397344Z vector_internal_metrics_cardinality_total{} = 123
2022-10-14T18:45:43.754703667Z vector_internal_metrics_cardinality{} = 88
2022-10-14T18:45:43.754703667Z vector_internal_metrics_cardinality_total{} = 88
2022-10-14T18:45:53.754270501Z vector_internal_metrics_cardinality{} = 87
2022-10-14T18:45:53.754270501Z vector_internal_metrics_cardinality_total{} = 87
2022-10-14T18:46:03.757142293Z vector_internal_metrics_cardinality{} = 127
2022-10-14T18:46:03.757142293Z vector_internal_metrics_cardinality_total{} = 127
2022-10-14T18:46:13.754931618Z vector_internal_metrics_cardinality{} = 11194
2022-10-14T18:46:13.754931618Z vector_internal_metrics_cardinality_total{} = 11194
2022-10-14T18:46:23.754441473Z vector_internal_metrics_cardinality{} = 13301
2022-10-14T18:46:23.754441473Z vector_internal_metrics_cardinality_total{} = 13301
2022-10-14T18:46:33.755123195Z vector_internal_metrics_cardinality{} = 13277
2022-10-14T18:46:33.755123195Z vector_internal_metrics_cardinality_total{} = 13277
2022-10-14T18:46:43.754776057Z vector_internal_metrics_cardinality{} = 8946
2022-10-14T18:46:43.754776057Z vector_internal_metrics_cardinality_total{} = 8946
2022-10-14T18:46:53.754269426Z vector_internal_metrics_cardinality{} = 1446
2022-10-14T18:46:53.754269426Z vector_internal_metrics_cardinality_total{} = 1446
2022-10-14T18:47:03.754606524Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:47:03.754606524Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:47:13.754874275Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:47:13.754874275Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:47:23.754788715Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:47:23.754788715Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:47:33.754933493Z vector_internal_metrics_cardinality{} = 84
2022-10-14T18:47:33.754933493Z vector_internal_metrics_cardinality_total{} = 84
2022-10-14T18:47:43.754277191Z vector_internal_metrics_cardinality{} = 84
2022-10-14T18:47:43.754277191Z vector_internal_metrics_cardinality_total{} = 84
2022-10-14T18:47:53.754912266Z vector_internal_metrics_cardinality{} = 84
2022-10-14T18:47:53.754912266Z vector_internal_metrics_cardinality_total{} = 84
2022-10-14T18:48:03.755184292Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:48:03.755184292Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:48:13.754574781Z vector_internal_metrics_cardinality{} = 10580
2022-10-14T18:48:13.754574781Z vector_internal_metrics_cardinality_total{} = 10580
2022-10-14T18:48:23.754456408Z vector_internal_metrics_cardinality{} = 13273
2022-10-14T18:48:23.754456408Z vector_internal_metrics_cardinality_total{} = 13273
2022-10-14T18:48:33.754552875Z vector_internal_metrics_cardinality{} = 13273
2022-10-14T18:48:33.754552875Z vector_internal_metrics_cardinality_total{} = 13273
2022-10-14T18:48:43.754068495Z vector_internal_metrics_cardinality{} = 8768
2022-10-14T18:48:43.754068495Z vector_internal_metrics_cardinality_total{} = 8768
2022-10-14T18:48:53.755112553Z vector_internal_metrics_cardinality{} = 1755
2022-10-14T18:48:53.755112553Z vector_internal_metrics_cardinality_total{} = 1755
2022-10-14T18:49:03.754170984Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:49:03.754170984Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:49:13.754755707Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:49:13.754755707Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:49:23.754936061Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:49:23.754936061Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:49:33.754461666Z vector_internal_metrics_cardinality{} = 108
2022-10-14T18:49:33.754461666Z vector_internal_metrics_cardinality_total{} = 108
2022-10-14T18:49:43.754534858Z vector_internal_metrics_cardinality{} = 108
2022-10-14T18:49:43.754534858Z vector_internal_metrics_cardinality_total{} = 108
2022-10-14T18:49:53.754511359Z vector_internal_metrics_cardinality{} = 108
2022-10-14T18:49:53.754511359Z vector_internal_metrics_cardinality_total{} = 108
2022-10-14T18:50:03.755056135Z vector_internal_metrics_cardinality{} = 377
2022-10-14T18:50:03.755056135Z vector_internal_metrics_cardinality_total{} = 377
2022-10-14T18:50:13.754080971Z vector_internal_metrics_cardinality{} = 12428
2022-10-14T18:50:13.754080971Z vector_internal_metrics_cardinality_total{} = 12428
2022-10-14T18:50:23.754709299Z vector_internal_metrics_cardinality{} = 13137
2022-10-14T18:50:23.754709299Z vector_internal_metrics_cardinality_total{} = 13137
2022-10-14T18:50:33.754983973Z vector_internal_metrics_cardinality{} = 12933
2022-10-14T18:50:33.754983973Z vector_internal_metrics_cardinality_total{} = 12933
2022-10-14T18:50:43.755122780Z vector_internal_metrics_cardinality{} = 8834
2022-10-14T18:50:43.755122780Z vector_internal_metrics_cardinality_total{} = 8834
2022-10-14T18:50:53.754949156Z vector_internal_metrics_cardinality{} = 489
2022-10-14T18:50:53.754949156Z vector_internal_metrics_cardinality_total{} = 489
2022-10-14T18:51:03.754900224Z vector_internal_metrics_cardinality{} = 87
2022-10-14T18:51:03.754900224Z vector_internal_metrics_cardinality_total{} = 87
2022-10-14T18:51:13.754126784Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:51:13.754126784Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:51:23.754334349Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:51:23.754334349Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:51:33.754650923Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:51:33.754650923Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:51:43.754829407Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:51:43.754829407Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:51:53.754080809Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:51:53.754080809Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:52:03.755068496Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:52:03.755068496Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:52:13.756146437Z vector_internal_metrics_cardinality{} = 11339
2022-10-14T18:52:13.756146437Z vector_internal_metrics_cardinality_total{} = 11339
2022-10-14T18:52:23.754635679Z vector_internal_metrics_cardinality{} = 13485
2022-10-14T18:52:23.754635679Z vector_internal_metrics_cardinality_total{} = 13485
2022-10-14T18:52:33.754905470Z vector_internal_metrics_cardinality{} = 13485
2022-10-14T18:52:33.754905470Z vector_internal_metrics_cardinality_total{} = 13485
2022-10-14T18:52:43.755015421Z vector_internal_metrics_cardinality{} = 7205
2022-10-14T18:52:43.755015421Z vector_internal_metrics_cardinality_total{} = 7205
2022-10-14T18:52:53.755024474Z vector_internal_metrics_cardinality{} = 2047
2022-10-14T18:52:53.755024474Z vector_internal_metrics_cardinality_total{} = 2047
2022-10-14T18:53:03.754434307Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:53:03.754434307Z vector_internal_metrics_cardinality_total{} = 83
2022-10-14T18:53:13.754387272Z vector_internal_metrics_cardinality{} = 83
2022-10-14T18:53:13.754387272Z vector_internal_metrics_cardinality_total{} = 83
```

Is there anything else you want me to do to help with the troubleshoot?

**Comment by leandrojmp** [comment]
Hello @jszwedko,

Is there anything else I can try to fix this memory leak problem?

**Comment by jszwedko** [comment]
Hi @leandrojmp !

Given that metrics _do_ seem to be being expired here. I'll close this specific issue, but also reopen https://github.com/vectordotdev/vector/issues/11025 to track this issue. One thing you could do, if very motivated, is run Vector under a memory profiler like like heaptrack (see https://nnethercote.github.io/perf-book/profiling.html) and then share the resulting profile with us. Given that information we might be able to more easily narrow down the issue.
