### ISSUE TITLE
Vector calls to journalctl causing spammy logs

### ISSUE THREAD

**Issue by nf-brentsaner** [vectordotdev/vector#23028]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Problem

When using a `journald` source on e.g. AlmaLinux 9.5 (systemd/journald 252), many many messages are written to the local log like such:

```
May 11 07:12:40 [REDACTED] vector[1193228]: 2025-05-11T07:12:40.791850Z  INFO source{component_kind="source" component_id=journald_remote component_type=journald}: vector::sources::journald: Starting journalctl.
May 11 07:12:40 [REDACTED] journalctl[1465017]: Data from the specified boot (+0) is not available: No such boot ID in journal
May 11 07:12:40 [REDACTED] vector[1193228]: 2025-05-11T07:12:40.798491Z  WARN source{component_kind="source" component_id=journald_remote component_type=journald}: vector::sources::journald: Journalctl process stopped.
```

If one is capturing local journald logs in Vector, this obviously creates a particularly vexing situation as those logs are filled with junk entries like the above, ironically created by the exact mechanism designed to capture them.

This occurs regardless of the setting of `current_boot_only`, though per #18068 this is likely to be expected.

Instead, this seems to be an invocation syntax bug from Vector to the journalctl call itself.
For example:

```
# journalctl --list-boots
IDX BOOT ID                          FIRST ENTRY                 LAST ENTRY
 -1 00d349cb80f5472fa082901dfcf1b38f Sun 2025-04-27 22:32:57 UTC Sat 2025-05-03 06:30:49 UTC
  0 a1fa11402ef049cf8b6474cfeeefc859 Sat 2025-05-03 06:30:52 UTC Sun 2025-05-11 07:17:45 UTC
```

There is indeed a `0` entry there, but `+0` seems to be invalid syntax.
I am unable to replicate this at the shell by any of the following:

* `journalctl --follow --boot`
* `journalctl --follow`
* `journalctl --follow --boot=+0`

So I'm not quite sure what exact syntax is being invoked.

### Configuration

```text
# /etc/vector/sources/from_journald.yml

type: journald
current_boot_only: False
```

### Version

vector 0.46.1 (x86_64-unknown-linux-gnu 9a19e8a 2025-04-14 18:36:30.707862743)

### Debug Output

```text
(Unable to stop currently running Vector instance due to availability guarantees, but this is reproducible on every instance I've tried on matching above versions/environments.)
```

### Example Data

See above

### References

* #18068

**Comment by Antiarchitect** [comment]
It seems like I have similar issue. Vector starts spamming 
```
Starting journalctl.
Journalctl process stopped.
```
Just some high-intesity logs from docker rootless containers - nothing special. Relatively high rate of them.
Systemd 249 on CentOS fork.

Calling `journalctl -f` from the shell do not cause it fail in several minutes as vector messages appear about once a minute or even more oftenly.

@nf-brentsaner Have found the solution/workaround since May 11?

Vector 0.35.0

UPD: It seems like actual rate was 20k/sec though :) as I raised limits to 100k/sec there was no suppression messages :) But even so error shouldn't appear and describes actual situation badly.

**Comment by nf-brentsaner** [comment]
> (SNIP)
> 
> @nf-brentsaner Have found the solution/workaround since May 11?

Unfortunately not. I toyed with either adding in some intermediary/middleware service before it hits Vector, which seemed largely silly, or coming up with a VRL transform to parse it (which is... suboptimal). I've not had time to do either, though IMHO it makes sense to have this fixed via a VRL parser just like `parse_syslog()`, which there is an open request for (I link to it in my original post for this issue).

**Comment by Antiarchitect** [comment]
@nf-brentsaner IMHO VRL workarounds would have high CPU consumption on my rates. It would be nice it be fixed in it's core.
BTW, do you have 
```
Storage=persistent
```
in your JournalD config?
And do you have `acknowledgements: yes` enabled in your Vector config?

I have a theory that at this rate relatively small journald files (~80MB) are filled too quickly and Vector somehow doesn't have time to read from journald before an oldest one is GC'ed and Vector checkpoints become invalid. But why the error is so strange?

**Comment by nf-brentsaner** [comment]
> @nf-brentsaner IMHO VRL workarounds would have high CPU consumption on my rates. It would be nice it be fixed in it's core.
> BTW, do you have 
> ```
> Storage=persistent
> ```
> in your JournalD config?

Not sure if I wasn't clear in the opening post, but this is for *journald-remote* logs, wherein remote hosts (e.g. `hostA`) send to the Vector server (e.g. `hostB`) via https://www.freedesktop.org/software/systemd/man/latest/systemd-journal-upload.service.html and are received by https://www.freedesktop.org/software/systemd/man/latest/systemd-journal-remote.service.html

For example:

`hostA:/etc/systemd/journal-upload.conf.d/vector.conf`:

```
[Upload]
URL=https://hostA:19532
TrustedCertificateFile=/etc/systemd/journal-remote.conf.d/pki/ca.pem
ServerKeyFile=/etc/systemd/journal-remote.conf.d/pki/key.pem
ServerCertificateFile=/etc/systemd/journal-remote.conf.d/pki/cert.pem
NetworkTimeoutSec=120
```

`hostB:/etc/systemd/journal-remote.conf.d/vector.conf`:

```
[Remote]
Seal=false
SplitMode=host
ServerKeyFile=/etc/systemd/journal-remote.conf.d/pki/key.pem
ServerCertificateFile=/etc/systemd/journal-remote.conf.d/pki/cert.pem
TrustedCertificateFile=/etc/systemd/journal-remote.conf.d/pki/ca.pem
```

`hostB:/etc/vector/sources/journald_remote.yml`:

```
type: journald
journal_directory: '/var/log/journal-remote'
since_now: False
extra_args:
  - '--merge'
```

But this generally oughtn't matter, as Vector seems to parse journald files via `journalctl` instead of directly parsing. The junk journald messages in the journal for `hostB` are due to Vector invoking `journalctl` with bad arguments past a certain systemd version, AFAICT.

De facto, remote logs WOULD technically have the same effect as "persistent", I guess, since they're written to disk in the same format as `Storage=persistent` would for the local host. But `Storage=volatile` writes them in the same format. The literal only differences are the path journald writes to, with the latter being a RAM-backed FS/mount.

Having a native "journald wire format parser" in Vector would get around Vector needing to call `journalctl` entirely (`Storage=volatile` still "writes" logs, they just go to `/run/journal/`) AND would very easily be exposed via a `parse_journald()` Vector VRL func, allowing one to just specify an `http_server` source and parsing in a VRL transform (completely removing the need for running `systemd-journal-remote.service` which is...flaky at best) ANR/OR just done via the way I configure it above.

(See also: [journald export format](https://systemd.io/JOURNAL_EXPORT_FORMATS/#journal-export-format), [journald disk format](https://systemd.io/JOURNAL_FILE_FORMAT/))

The main issue, though, in either/any case seems to be actual journalctl invocation in Vector.

> And do you have `acknowledgements: yes` enabled in your Vector config?

Nope.

> 
> I have a theory that at this rate relatively small journald files (~80MB) are filled too quickly and Vector somehow doesn't have time to read from journald before an oldest one is GC'ed and Vector checkpoints become invalid. But why the error is so strange?

I'm not sure this is the cause. I can manually reproduce the issue if I invoke journalctl with the same evaluated invocation args that Vector calls journalctl with IIRC.

**Comment by Antiarchitect** [comment]
@nf-brentsaner Din't read your first message carefully. Anyway if it's incompatibility between Vector version (journalctl invocation arguments) and systemd version what bothers me in my case is:
1. Problem appears only under a high load (one of the services on the server gone mad). Other servers feel well.
3. I have very old Vector 0.35.0 and systemd 249 and you have relatively fresh Vector 0.46.1 and Systemd 252 and still it's like vector uses wrong arguments invoking journalctl.
Will try to investigate it from my side. If I find out anything useful - will write it here. Thank you for your time :)

**Comment by nf-brentsaner** [comment]
> @nf-brentsaner Din't read your first message carefully. Anyway if it's incompatibility between Vector version (journalctl invocation arguments) and systemd version what bothers me in my case is:
> 1. Problem appears only under a high load (one of the services on the server gone mad). Other servers feel well.
> 3. I have very old Vector 0.35.0 and systemd 249 and you have relatively fresh Vector 0.46.1 and Systemd 252 and still it's like vector uses wrong arguments invoking journalctl.
> Will try to investigate it from my side. If I find out anything useful - will write it here. Thank you for your time :)

You may instead be experiencing something more closely related to #18068 directly. Our environments differ a significant amount, and I suspect your Vector may be too old to be related to what I'm seeing here.

I'd have to check, but I'm fairly certain *this* issue (#23028) is actually still occurring in the most recent Vector.
I recommend you open a separate/different issue for your environment if your issue still occurs on most recent Vector (0.48.0).

**Comment by nf-brentsaner** [comment]
I have confirmed that the issue I have reported in the original post for this issue still occurs on Vector 0.48.0 with systemd 257.7.
